---
# defaults file for web_server_setup
domain: domain.com

php_version: 7.2

php_modules:
   - php{{ php_version }}-mysql
   - php{{ php_version }}-curl
   - php{{ php_version }}-common
   - php{{ php_version }}-mbstring
   - php{{ php_version }}-gd
   - php{{ php_version }}-xml
   - php{{ php_version }}-cli
   - php{{ php_version }}-zip
   - php{{ php_version }}-json

#mysql_admin_pass: qwe

generate_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
   