---
- name: Web Server setup for SkaDate software
  hosts: aws_test
  become: yes

  vars_prompt:
    - name: "domain"
      prompt: "Enter Domain name"
      private: no
  
  roles:
    - { role: web_server_setup, when: ansible_os_family == 'Debian' }
