---
# tasks file for web_server_setup
  - name: Info
    debug: 
      msg: 
      - "System:  {{ansible_lsb.description}}"
      - "IP:      {{ansible_enp0s3.ipv4.address}}"
      - "Domain: {{ domain }}"

  - name: apt update
    apt:  
      update_cache: yes
     
 # Install nginx server      
  - include: nginx.yml
  
 # Install PHP      
  - include: php.yml  
  
   # Install MySQL (MariaDB)      
  - include: mysql.yml  
  
  - name: Copy phpinfo
    copy: 
      src: index.php 
      dest: /var/www/html/index.php 
      mode: 0664
      
  - name: Create file with details      
    template: 
      src: details.j2 
      dest: details.txt
    delegate_to: 127.0.0.1      
 # ------------      
 
